version: '3.8'

services:
  # Frontend Service
  frontend:
    build:
      context: ./traveldesk/traveldesk/frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  # Backend Service  
  backend:
    build:
      context: ./Travel_desk_backend/Travel_desk_backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=database;Database=TravelDeskDB;User Id=sa;Password=YourPassword123!;TrustServerCertificate=true;
    depends_on:
      - database

  # Database Service
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123!
      - MSSQL_PID=Express
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
