version: '3.8'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "TravelDesk123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P TravelDesk123! -C -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./Travel_desk_backend/Travel_desk_backend/TravelDesk_Api
    ports:
      - "5088:5088"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=database;Database=TravelDeskDB;User Id=sa;Password=TravelDesk123!;TrustServerCertificate=true;

  frontend-dev:
    build:
      context: ./traveldesk/traveldesk/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ./traveldesk/traveldesk/frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  sqldata:
